export const variable_options = ['DOM_fluorescence', 'EC50', 'FeII_formation_rates',
'Gibbs_free_energy', 'LC50', 'LOEC', 'NOEC', 'PAR', 'PNEC',
'Standard_reduction_potential', 'alkalinity', 'ammonium-nitrogen',
'areal_hypolimnetic_mineralization_rate', 'assimilable_organic_carbon',
'bacteria_abundance', 'c_to_n_ratio', 'capillary_suction_time',
'chemical_oxygen_demand', 'chlorophyll_fluorescence', 'color',
'concentration', 'count', 'current', 'degradation_rate', 'delta_13C',
'delta_15N', 'discharge', 'dissolved_inorganic_carbon',
'dissolved_organic_carbon', 'dissolved_oygen',
'dissolved_reactive_phosphate', 'electric_conductivity',
'faecal_sludge_accumulationrate', 'flow_cytometric_cell_counts',
'fluorescence', 'fraction', 'gene_abundance', 'grain_size',
'groundwater_recharge_rate', 'growth_rate', 'hydraulic_conductivity',
'illuminance', 'length', 'light_scattering',
'methanotroph_cell_counts', 'mortality', 'net_ecosystem_production',
'none', 'odor', 'organic_phosphorus', 'oxidation_kinetcis',
'oxygen_saturation', 'pH', 'phycocyanin_fluorescence',
'potential_methane_oxidation_rates', 'precipitation', 'pressure',
'relative_humidity', 'respiration', 'salinity', 'scintillation_counts',
'secci_depth', 'sludge_blanket_accumulation_rate', 'solar_radiation',
'suspended_material', 'temperature', 'texture', 'tke_dissipation_rate',
'total_cell_concentration', 'total_hardness',
'total_kjeldahl_nitrogen', 'total_nitrogen', 'total_organic_carbon',
'total_phosphorus', 'total_solids', 'total_solids_after_dewatering',
'turbidity', 'velocity', 'volatile_solids', 'volumetric_flow_rate',
'waterlevel', 'weight', 'wind_speed'];

export default {
  variable_options,
};
